# AWS ECS Task Definition (Fargate)
# This can be used with AWS ECS, EKS, or App Runner
version: '1'

# Environment variables for AWS deployment
environment:
  # Application settings
  - name: PORT
    value: "8000"
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: ENVIRONMENT
    value: "production"
  
  # OpenAI API Key (set in AWS Secrets Manager)
  - name: OPENAI_API_KEY
    valueFrom: "arn:aws:secretsmanager:region:account:secret:hr-assistant/openai-api-key"

# Resource requirements
cpu: 1024      # 1 vCPU
memory: 2048   # 2 GB RAM

# Port mapping
ports:
  - containerPort: 8000
    protocol: tcp

# Health check
healthCheck:
  command:
    - "CMD-SHELL"
    - "curl -f http://localhost:8000/health || exit 1"
  interval: 30
  timeout: 5
  retries: 3
  startPeriod: 60

# Logging
logConfiguration:
  logDriver: awslogs
  options:
    awslogs-group: "/ecs/hr-assistant"
    awslogs-region: "us-east-1"
    awslogs-stream-prefix: "ecs"